### ISSUE TITLE
2.0.8.1b: Fallout 4 DLC plugins do not remain active after running LOOT v0.10.2

### ISSUE THREAD

**Issue by fireundubh** [LePresidente/modorganizer#12]
### Conditions to Reproduce

* One or more Fallout 4 DLC plugins installed
* All available Fallout 4 DLC plugins activated

### Steps to Reproduce

1. Run LOOT v0.10.2 through MO.
2. Sort and apply the new sort order.
3. Exit LOOT.

### Result

* All Fallout 4 DLC plugins are deactivated.
* All Fallout 4 DLC plugins are deactivated regardless of whether their load orders are locked. (Although, technically, locking load order has nothing to do with preventing deactivation, but the locked flag icon can be misinterpreted as a plugin state lock.)

**Comment by pressure68** [comment]
This is because of how DLC loading was changed for FO4 and SSE. They are no longer listed in plugins.txt, so LOOT doesn't put them their either. Since they are gone from the list after running LOOT, MO2 shows them as disabled.

Apparently MO2 needs to now assume for FO4 and SSE that the DLC will always be loading if present, and keep them enabled at all times, just like the game does.

**Comment by LePresidente** [comment]
I see someone has already commited the fix for this in the fallout 4 plugin "https://github.com/TanninOne/modorganizer-game_fallout4/commit/880025f4bce44f4fd37386de4e9194d6224dc9d9#diff-607fcd03d8aaa5d6e6ec5ec939e68b72" will test it today

**Comment by LePresidente** [comment]
Will test this later today, if @pressure68 is correct will port the changes I did for skyrimSE across to the  fallout4 plugin.
