### ISSUE TITLE
Missing "Have MO manage archives" checkbox

### ISSUE THREAD

**Issue by yoyokenny** [LePresidente/modorganizer#171]
# The problem

Missing "Have MO manage archives" checkbox

# Environment

Mod Organizer v2.1.0.1
Windows 7 64-Bit Home Premium

# Details

Can not manage BSA's that have had the empty plugin disabled in the load order, due to the "Have MO manage archives" checkbox being missing. BSA's cannot be enabled/disabled in Archives tab.

**Comment by GrantSP** [comment]
You're not supposed to be able to manage BSAs in MO2 in the same way you could with MO.
The "Archives" tab was restored only to provide greater conflict resolution information.

**Comment by yoyokenny** [comment]
Then how is it supposed to be done? Empty plugins take up valuable plugin slots when doing modpack installs like STEP. The BSA's still need to be loaded.

**Comment by GrantSP** [comment]
Take note of the reason Tannin removed it as he outlines [here](http://forum.step-project.com/topic/9377-mod-organizer-2-discussion-and-feedback/#entry147003).

The team are now re-instating some of the backend features to aid in seeing which files are supplied by which mod, DLC or otherwise.
The entire tab will likely be removed in later releases.

Yes there does need to be a plugin to load those assets but the benefits of doing so outweigh any issues that MO may introduce.

**Comment by Silarn** [comment]
I'll also note than empty ESLs should take negligible mod space for all but the most extreme setups.
