### ISSUE TITLE
[Enhancement] Have NXMHandler invoke the correct game instance upon download

### ISSUE THREAD

**Issue by GrantSP** [LePresidente/modorganizer#210]
**Overview**
The way MO2 handles downloads now is determined by the last invoked game instance used. If this behaviour could be changed it would ease use with multiple games.

**Details**
If the user has MO2 setup for multiple games it is only the last instance used that is recognised when you invoke a download from Nexus via the "Download with manager" button.
ie. Assuming the last time MO2 was open it was for Fallout 4, and you then close it down and do something else. When you now visit Nexus and are on any other game page, e.g. Skyrim, and then try to get a mod to download MO2 will complain that it is on the wrong game.

If MO2 could somehow start in the game instance that matches the invoked call from NXMHandler it would bypass the need to switch MO2 instances manually and retry the download.

Not sure of the complexity of this or even if it is possible.

**Comment by erasmux** [comment]
This has already been implemented and works well. For completeness I will detail below how the current system works and its limitations. If you are not getting this behavior fix your nxmhandler setup and/or make sure the nxmhandler.exe which is registered to handle the links is from an updated MO2 release.

When you click on a nexus download link and nxmhandler is registered for handling these links:
- If no MO instance is currently open, then nxmhandler will open the MO instance registered for this game (usually you will only have one for each game, but if you have more than one the first one from the top of the list nxmhandler displays will "win").
- If an MO instance is already open it will get this link and if the link is for a different game it will complain about it. (Technically, nxmhanlder will still forward the link to the correct instance but since only one MO instance can be opened at any time, it will forward the link to the currently open instance).

**Comment by GrantSP** [comment]
You know I was thinking there was something fishy going on as the display of my nxmhandler looked nothing like that of another user's, @GSDFan, that posted a comment in STEP just yesterday.
His looks like this:
http://forum.step-project.com/uploads/monthly_01_2018/post-1366-0-19544000-1516536083.png
whereas mine looks like this:
![nxmhandler](https://user-images.githubusercontent.com/3291695/35200566-104f2172-ff65-11e7-8212-58996e7971a1.png)
All the games lumped together. I'd not seen this with MO1 that used to maintain them correctly regardless of which nxmhandler I used. ie. from whatever MO install for whatever game the ini was always set correctly.

I'll see if I can unclump them and get it to work properly

**Comment by GrantSP** [comment]
Nope something is wrong on my setup. Even after changing the nxmhandler to point to the correct game I am presented with this error dialogue:
![wrong-game](https://user-images.githubusercontent.com/3291695/35200639-2ba85e06-ff66-11e7-9d3c-ffec082f5fca.png)
and the nxmhandler reverts to how it is above.

**Comment by Silarn** [comment]
Having the games on one line is completely valid - though it will only work correctly with an instanced setup where one exe handles all games. If you run a portable setup then each game should point to its corresponding MO instance. Again, since only one instance of MO can be open at once you will have to close the current instance if you wish to download for a different game (or swap to the game you intend to use).

If you believe you've already switched to the correct game then most likely your instance is configured incorrectly and needs to be fixed to point to the proper game.
