### ISSUE TITLE
Feature Request: Allow the use of external LOOT binaries when using build in Sort button

### ISSUE THREAD

**Issue by avoitishin** [LePresidente/modorganizer#241]
Allow the use of external LOOT binaries when using build in Sort button

**Comment by Al12rs** [comment]
The sort button uses the loot api, and unless they changed too much you should be able to update it to the latest loot api version.

**Comment by SuperSandro2000** [comment]
I tried this with the 0.12.4 API and it didn't work. The two binaries I almost 1MB in size difference. If you want the latest API hop on discord. There is a build with it up.

**Comment by SuperSandro2000** [comment]
Grab the dll from here: https://github.com/loot/loot-api/releases
It should work but we are not supporting it in anyway. Mod Organizer will always try to ship releases with the latest Loot API.

**Comment by Silarn** [comment]
You need to use the 64 bit version. Loot is packaged with the 32 bit version and is incompatible.

**Comment by Silarn** [comment]
Unless there's a command line argument to automatically sort instead of launching the GUI, I'm not sure this request is feasible.

**Comment by SuperSandro2000** [comment]
The loot-api releases page I linked has a 64 bit variant. He would simply need to replace that in his mo installation. 
If we wanted to use an external exe like @Silarn suggested (what would be pointless because of my above solution and the ability to use loot trough the normal executables) @WrinklyNinja would have to implement that. 
Currently loot only supports these arguments:
defaultGame, lootDataPath, url

This is very low priority as their are easy work arrounds and we update loot api regularly anyway.

**Comment by Silarn** [comment]
Right. That's basically what I'm saying. Using external loot binaries, as stated, is not particularly feasible. In addition, while newer API builds/releases often do work when dropped in, there are sometimes breakages that require updates to lootcli. Or changes that may continue to work but might introduce some edge case bugs that need attention. (For instance, the change in the settings file format.)
