### ISSUE TITLE
Lost >100 mods while moving MO2 from "C:" to "D:"

### ISSUE THREAD

**Issue by RambunctiousKid** [LePresidente/modorganizer#248]
I attempted to move the entire, "Mod Organizer" file from my "C:" directory into my "D:" directory, simply because it had 100s of gb more space left. I dragged the MO file onto my desktop, and then into the very first screen that appears when you click "D:". I heard that, when doing this, you have to delete the main .ini for the program (not nxmhandler.ini), so I did. After I booted up Mod Organizer 2, my load order went from around 210 mods, to 76 mods, all of which were unmanaged, due to them being installed on NMM first. I've found the file with all the MO2 installed mods, but I don't know how to re-integrate them into the program. I've tried taking the whole ModOrganizer file back into the, "C:\Users\Name\AppData\Local " file, but they have not re-appeared in the program itself. I also can not force the program to completely reboot, as the modorganizer.ini (or whatever) will not reappear.

**Comment by Al12rs** [comment]
Mo is not really supposed to be used over an existing setup since we can't support all the problems that come with it, but leaving that aside, it just seems to me like you need to update your Mods path in the Mo settings. Where was your mods directory before you moved the mo folder? You simply need to find that folder and either move it so leave it there and then point Mo to its path in the settings.

**Comment by Al12rs** [comment]
You are not supposed to move around the installation and the program does not support it. You should be able to but that though, but only supposing you know what you are doing. This is not a problem caused by Mo having a bug or something. If there is indeed something that is not behaving as expected I will reopen this.
