### ISSUE TITLE
[Feature Request] Disable the "MO is locked" dialogue via a setting.

### ISSUE THREAD

**Issue by GrantSP** [LePresidente/modorganizer#262]
Whilst that message is probably very helpful for a great many users that just play the game, for power users it gets annoying very quickly to have to click that and get back into MO to access another tool whilst modding the game.

If there could be a setting to disable it, either for just that session or permanently, that would ease workload somewhat.
Perhaps adding a checkbox in the "Executables" setup dialogue to have that specific executable not trigger it.

**Comment by SuperSandro2000** [comment]
TL;DR: rejected due to technically reason
This was discussed a while back in the discord and you probably missed it but the suggestion got rejected because the window is there for a reason. usvfs is quite complex and you shouldn't mess with it while it is running. Most people would check that box for convince and probably more things go wrong. For more technically details you would need to ask Eran or Silarn.

**Comment by Al12rs** [comment]
I'm afraid Sandro is right. This is not something people should do, even experts. Especially running two external programs at the same time it undefined behaviour. We will not support it.
