### ISSUE TITLE
Unable to run Sky Proc Patchers

### ISSUE THREAD

**Issue by blomstertj** [LePresidente/modorganizer#3]
I believe this is a bug carried over from the original branch.  For example, the Dual Sheath Patch does not run with Mod Organizer 2 properly.  It doesn't load all the plugins and complains about missing masters.

**Comment by LePresidente** [comment]
@blomstertj  Can you verify this is still the case with the latest version?

**Comment by blomstertj** [comment]
@LePresidente I can

**Comment by ZachHaber** [comment]
So, the problem seems to stem from the changes to the new virtual file system. A workaround for now: set up the directories in the skyrim data folder, so "C:\Program Files (x86)\Steam\SteamApps\common\Skyrim\Data\SkyProc Patchers\Dual Sheath Redux Patch" is a valid path if you are using dual sheath redux (assuming normal steam folder location). 
Then set the skyproc patcher's start in to that path.
I believe what is happening is that the start in folder doesn't get mapped to the appropriate spot in the virtual file system, so it tries to run it from your mod organizer installation location, which unsurprisingly doesn't have all the plugins and masters.

**Comment by blomstertj** [comment]
So your saying to create a directory for SkyPro in the game data directory? What do you mean by set the start in? Do you mean from MO as an executable?

**Comment by ZachHaber** [comment]
Yes, create the directories for the skyproc .jar files in the game data directory. You don't need to place anything in them, just have them there.
In the gearbox button, with the modify executables, click on the skyproc patcher's name. There will be a title, binary, start in, and arguments. You need to modify the start in to point to the game data directory at the directory you just made.
Keep in mind that MO will crash if you launch it twice, because of #10

**Comment by blomstertj** [comment]
@ZachHaber
That's what I figured you meant. I will try that as well.

**Comment by blomstertj** [comment]
@LePresidente 
I ran the SkyProc patcher through MO this way: 
![image](https://cloud.githubusercontent.com/assets/19897967/22132261/7df7f586-de7e-11e6-8c58-d2b5efe5b72f.png)
But it complains about missing masters.
I added it as an executable and I have the same error.

@ZachHaber 
Your method works correctly and I'm able to create the patch and it imports all my mod plugins.
