### ISSUE TITLE
Virtual Install not working very frequently launching SSE

### ISSUE THREAD

**Issue by MaddBomber83** [LePresidente/modorganizer#35]
MO2 is becoming rather frustrating.  The features just outweigh the stability of NMM.

I am getting very frequent 'misses' when launching SSE either through MO2 or its desktop link.  The virtual data folder just doesn't carry forward and the launch of SSE is Vanilla.  After this happens once, it is very hard to get rid of.

Sometimes a file cleaner will help; shutting down MO2; using task manager to end 'ghost' MO2 or SSE processes.  Finally a computer restart sometimes fixes it.

I'm not even sure how to translate that into useful information for you.

**Comment by Anach** [comment]
It's not just SSE. Same happens with me and FO4. I agree that the program is very buggy and unstable, but even with that, the mod management is far superior to NMM, and NMM feature wise has got worse over the years, rather than better. NMM is just a mod installer for dummies.

MO is still working for me with FO4, and all my mods are loading, however, none of the tools will. They initially worked, but then one day suddenly stopped and I haven't been able to get them functioning again so far. That includes LOOT, FO4Edit, Bodyslide, none of them show any mod content.

What do you mean by "a file cleaner"?

**Comment by MaddBomber83** [comment]
CCleaner or some tools like Bitdefender's / Revo Uninstaller's Junk File Finder.  Basically clearing out the temporary directory.

I've stopped using any MO desktop links.  Instead I find launching MO and then 1 tool through MO works most of the time.  I then exit MO before launching another tool or the game.

Also, at a certain mod load (~120 ESPs for me) the LOOT sort in MO fails; but the launching Loot and sorting through that works just fine.  I think MO just does not give it enough time before calling it failed.

Have you tried removing (unconfiguring) all the tools and then re-adding them?  Also try to delete the MO INI in your Local\Mod Organizer folder.

**Comment by Anach** [comment]
Unfortunately I've tried all those already. Never used desktop shortcuts, have tried various configurations for fo4edit and loot, admin/no admin, even tried completely redoing MO's setup from a fresh install and new ini files. Unfortunately I just cant get those tools to see the MO VFS. I have around 220 plugins.
