### ISSUE TITLE
override folder ignored on launch

### ISSUE THREAD

**Issue by derossm** [LePresidente/modorganizer#43]
I don't know the procedure to reproduce, but this has happened a few times this week.

On opening MO2, it will not read the override folder (report it empty), and then when manually refreshing it will rediscover the files. Unfortunately, this causes the load order of any of those esp's to be lost and treated as new files (if there was not another version in an active mod being overridden, such as when modifying esp files with xEdit and they get moved to override leaving no copy in the mod folder to fall back to in this scenario).

**Comment by ZachHaber** [comment]
Did you change your override folder off of the default location in appdata?
If so, I think that the next version of MO should solve this. I can't confirm whether that's the case due to lack of steps to reproduce. My guess is that MO is trying to read from the original override folder in the appdata.
If not, I have no idea at the moment, and probably won't get to this very quickly until there I can reproduce this issue.

**Comment by Silarn** [comment]
Can anyone still replicate this error?
