### ISSUE TITLE
Unkillable "ModOrganizer.exe" process

### ISSUE THREAD

**Issue by Fl4sHNoX** [LePresidente/modorganizer#95]
Hi there,

I am currently experiencing a recurring problem that is quite annoying.
The problem has occurred quite a few times already and I wasn't able to find any sort of fix on the internet about it.
Almost I'd say 7 or 8 times out of 10 whenever I try to close Mod Organizer (I'm using the last build by the way), it crashes and can't be reopened simply letting me with the following message:

> An instance of Mod Organizer is already running.

The thing is, I do see the process named "ModOrganizer.exe" in my task manager process list but I'm not able to terminate it by any means as it either leaves me with the error (when using "cmd taskkill /f"):

> ERROR: The process "ModOrganizer.exe" with PID ***** could not be terminated.
> Reason: There is no running instance of the task.

Or when I try to kill it with another process manager like Task Hacker for example:

> Unable to terminate ModOrganizer.exe (PID *****): Attempt to access a process that is being stopped.

The only "solution" I currently have is to hard shutdown my computer (holding the power button) as it won't even log out, restart or just shutdown as it simply cannot get rid of the process and therefore waits for it to terminate.

Also a few times it even starts getting the default windows Task Manager in a "Not Responding" state as well as "explorer.exe" making my computer almost unusable till I decide to do a hard reset.

Like I said this issue has happened quite a few times already and I'm not willing to hard reset my PC ten times a day simply to be able to mod my game properly.

I hope that you'll be able to fix this issue as soon as possible or maybe give me an alternate solution meanwhile it's being fixed so that I can enjoy modding my game (I'm currently only modding Fallout 4 with this version of MO) without needing to do violence to my computer.

Thanks a lot in advance!

N.B.: As a side note I already posted this issue on the TanninOne/modorganizer version (4.2) but the same issue happens with the last version available of this fork (4.3).

**Comment by azraal** [comment]
I assume a task launched by mod organizer is keeping it from closin
Ok just to make sure, if you are on windows 8 or 10:
There are two tabs. One is "processus" I assume it's process and the other is "Détail"  no idea what would be the translation. Sometimes the program doesn't appear on the process tab but is still there on the "Détail" tab. Fallout 4 is good for that but I also had it when bodyslide had issues. Kill those remaining processes and try to kill mod organizer's process in "Détail".

If all else fail you can try to right click on modorganizer.exe in the list, you have the option to kill the task or kill the task tree.
(equivalent to  taskkill /f /t ...)
But if you already did all the rest, I doubt it will work

**Comment by Fl4sHNoX** [comment]
I'm on Windows 10 (Creator Update, latest build 1703).

Yes, thanks for taking the time to reply but sadly I already tried everything you've suggested (I'm assuming you're French as well, the tabs are simply named "processes" & "details").

I still can't wrap my head around how a program can't be killed even with root privileges, it just doesn't make any sense to me...

**Comment by azraal** [comment]
I am French indeed. 
The reason I see, is that another running program has handles to this process (it may be a parent process or child process, or an highly priviledge). In my case, for exemple it was fallout 4 
Maybe your antivirus the usual culprit since it latches on any processes. On the other hand it might also be explorer, when my old hard disk, started to feel it's age, explorer would try to read damaged clusters which were not reported as broken (it happened only with this one disk, I never kept one as long.) Anyway when explorer stubbornly get in his head something it cannot, you can be sure those issues would happen. Explorer is killable, but your antivirus might be something else...
I had a lot of problems like that with avast when I used it (more than ten years ago though).
Anyway you can try with the sysinternal's process as it shows the handles on the processes.
I don't know if it will help kill MO2 but at least it may help you see what is locking it....
Here is what I found, maybe it'll help:
https://superuser.com/questions/675789/how-to-kill-a-task-that-is-lacking-an-instance#1018549

Since for now lepresidente has an hard time working on those issues for several reasons, we might not get a modorganizer update anytime soon.

**Comment by ron-courtright** [comment]
First, I found you can kill ModOrganizer.exe from the command line on Windows 10 if you use the pid:  

taskkill /pid ##### /t

This appears to be like kill -9 "some-pid-number" on 'NIX.
So my experience with un-killable ModOrganizer is when there is a succession of dialogs that appear after exiting a game (usually Fallout 4; for some reason SkyrimSE is better behaved) and then trying to interact with the ModOrganizer UI.  This is always fatal to the program and sometimes leads to the sad condition of ModOrganizer being unable to exit in an orderly fashion.

**Comment by Silarn** [comment]
As with many of the crashing bugs on 2.0.8.3, this is likely due to the handle issues that are currently being worked on. Please try to use the latest builds posted on the Discord server and see if they resolve your problem.

**Comment by Silarn** [comment]
Please test/respond to this ticket within the next several days or I will close the ticket due to inactivity.
